### ISSUE TITLE
What's the _x function?

### ISSUE THREAD

**Issue by emfluencekc** [emfluenceindia/media-content-taxonomy#4]
https://github.com/emfluenceindia/media-content-taxonomy/blob/20a639ee8f58f47088c83dd57b5cca281db3630c/media-content-taxonomy-register.php#L21
https://github.com/emfluenceindia/media-content-taxonomy/blob/20a639ee8f58f47088c83dd57b5cca281db3630c/media-content-taxonomy-register.php#L22

**Comment by emfluenceindia** [comment]
Thank you once again for pointing this out. Since we are not considering language, the `_x()` function here is useless. Replaced with `__()`.

**Comment by emfluencekc** [comment]
Probably a good idea to declare a translation domain for your plugin.
